//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriskAutomation.TestDataSet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeriskAutomation.TestDataSet.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verisk@123.
        /// </summary>
        internal static string Author_Password {
            get {
                return ResourceManager.GetString("Author_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sjohn.
        /// </summary>
        internal static string Author_UserName {
            get {
                return ResourceManager.GetString("Author_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verisk@123.
        /// </summary>
        internal static string ISO_Admin_Password {
            get {
                return ResourceManager.GetString("ISO_Admin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stangudu.
        /// </summary>
        internal static string ISO_Admin_UserName {
            get {
                return ResourceManager.GetString("ISO_Admin_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verisk@123.
        /// </summary>
        internal static string Reviewer_Password {
            get {
                return ResourceManager.GetString("Reviewer_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jrani.
        /// </summary>
        internal static string Reviewer_UserName {
            get {
                return ResourceManager.GetString("Reviewer_UserName", resourceCulture);
            }
        }
    }
}
